# Generated by Django 4.0 on 2022-04-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=32)),
                ('student_name', models.CharField(max_length=32)),
                ('family_name', models.CharField(max_length=32)),
                ('inspection_time', models.DateTimeField()),
                ('inspection_result', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=32)),
                ('student_name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('has_star', models.BooleanField()),
                ('show_time', models.DateTimeField()),
            ],
        ),
    ]
